; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=sink -S < %s | FileCheck %s

; Upfront critical edge splitting enables sinking instructions whose only
; use is a PHI argument sourced from their own block -- previously this
; set SuccToSinkTo = current block -> null, blocking all sinking.

; Basic arithmetic sunk to the forwarding block created by splitting the
; critical edge entry->merge (entry has 2 succs, merge has 2 preds).
define i32 @sink_via_crit_edge(i1 %cond) {
; CHECK-LABEL: @sink_via_crit_edge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ENTRY_MERGE_CRIT_EDGE:%.*]]
; CHECK:       entry.merge_crit_edge:
; CHECK-NEXT:    [[X:%.*]] = add i32 1, 2
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ [[X]], [[ENTRY_MERGE_CRIT_EDGE]] ], [ 0, [[THEN]] ]
; CHECK-NEXT:    ret i32 [[PHI]]
;
entry:
  %x = add i32 1, 2
  br i1 %cond, label %then, label %merge

then:
  br label %merge

merge:
  %phi = phi i32 [ %x, %entry ], [ 0, %then ]
  ret i32 %phi
}

; A memory(read) call was additionally blocked by the mayReadFromMemory()
; guard at the multi-predecessor merge block.  Splitting the critical edge
; gives a unique-predecessor forwarding block that bypasses that guard.
declare i32 @readonly_fn() memory(read) nounwind willreturn

define i32 @sink_readonly_call_via_crit_edge(i1 %cond) {
; CHECK-LABEL: @sink_readonly_call_via_crit_edge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ENTRY_MERGE_CRIT_EDGE:%.*]]
; CHECK:       entry.merge_crit_edge:
; CHECK-NEXT:    [[X:%.*]] = call i32 @readonly_fn()
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ [[X]], [[ENTRY_MERGE_CRIT_EDGE]] ], [ 0, [[THEN]] ]
; CHECK-NEXT:    ret i32 [[PHI]]
;
entry:
  %x = call i32 @readonly_fn()
  br i1 %cond, label %then, label %merge

then:
  br label %merge

merge:
  %phi = phi i32 [ %x, %entry ], [ 0, %then ]
  ret i32 %phi
}

; Negative: instruction used on both outgoing paths -- NCD of uses equals
; the current block, so it must not be sunk.
define i32 @no_sink_uses_on_both_paths(i1 %cond) {
; CHECK-LABEL: @no_sink_uses_on_both_paths(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X:%.*]] = add i32 1, 2
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ENTRY_MERGE_CRIT_EDGE:%.*]]
; CHECK:       entry.merge_crit_edge:
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ [[X]], [[ENTRY_MERGE_CRIT_EDGE]] ], [ [[Y]], [[THEN]] ]
; CHECK-NEXT:    ret i32 [[PHI]]
;
entry:
  %x = add i32 1, 2
  br i1 %cond, label %then, label %merge

then:
  %y = add i32 %x, 1
  br label %merge

merge:
  %phi = phi i32 [ %x, %entry ], [ %y, %then ]
  ret i32 %phi
}
