#!/bin/bash
cmake -S llvm -B /data/compilers/llvm-project/build-dbg -G Ninja \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DLLVM_ENABLE_PROJECTS="clang;lld;mlir" \
    -DCLANG_DEFAULT_LINKER=lld \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DBUILD_SHARED_LIBS=ON \
    -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;SPIRV" \
    -DLLVM_OPTIMIZED_TABLEGEN=ON \
    -DLLVM_ENABLE_BINDINGS=OFF \
    -DLLVM_ENABLE_LLD=ON \
    -DCLANG_DEFAULT_CXX_STDLIB=libc++ \
    -DLLVM_ENABLE_LIBCXX=ON \
    -DLLVM_CCACHE_BUILD=ON
#-DCMAKE_INSTALL_PREFIX=/home/drank/dev/compilers/llvm
